config/routes.rb
BachApp::Application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :contact_requests, only: :create

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :edit, :update] do
      member do
          put :edit
      end
    end
    resources :courses, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
          put :edit
      end
    end
    resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  validates :name, :email, :message, presence: true
  validates :name, :email, length: { maximum: 50 }

  after_create :send_contact_email

  def send_contact_email
    ContactRequestMailer.contact_email(self).deliver
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_attached_file :document, styles: {thumb: ["100x100", :jpg]}
  validates_attachment_content_type :document, :content_type => /\Aimage\/.*\Z|\Aapplication\/pdf\Z/
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :check_admin_permissions
  before_action :find_course, only: [:edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "El curso se creó exitosamente"
      redirect_to admin_courses_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @course.update(course_params)
      flash[:notice] = "Curso editado"
      redirect_to admin_courses_path
    else
      render 'edit'
    end
  end

  def destroy
    @course.destroy
    redirect_to admin_courses_path
  end

  private

    def find_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :cost, :document, :registrable)
    end

end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < ApplicationController
  before_action :check_admin_permissions
  before_action :find_entry, only: [:edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:notice] = "El curso se creó exitosamente"
      redirect_to admin_entries_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @entry.update(entry_params)
      flash[:notice] = "Curso editado"
      redirect_to admin_entries_path
    else
      render 'edit'
    end
  end

  def destroy
    @entry.destroy
    redirect_to admin_entries_path
  end

  private

    def find_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:url).merge(user_id: current_user.id)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin_permissions
  before_action :find_user, only: [:edit, :update]

  def index
    @users = User.all
    # if params[:query]
    #   @query = params[:query]
    #   @users = @users.search(params[:query])
    # end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Perfil editado"
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end


  protected

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :admin)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:name, :email, :password, :password_confirmation)
      end
    end

    def check_admin_permissions
      unless current_user.admin?
        return redirect_to root_path, alert: "¡Oops!No estás autorizado para administrar este sitio"
      end
    end

end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  def create
    @contact_request = ContactRequest.new(contact_request_params)

    redirect_to root_url
    if @contact_request.save
      flash[:notice] = "se ha enviado correctamente"
    else
      flash[:alert] = "No se pudo enviar. Intente nuevamente"
    end
  end

  private

  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact_request = ContactRequest.new
    @entries = Entry.all
    @courses = Course.all
  end
end

app/helpers/admin/entries_helper.rb
module Admin::EntriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_requests_helper.rb
module ContactRequestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/courses/edit.html.haml
.col-md-3.col-md-offset-4
  .text-center
    %h1 Editar curso
    %hr
  = simple_form_for @course, url: admin_course_url(@course), html: {method: :put, autocomplete: 'off' } do |f|
    = f.input :title, autofocus: true
    = f.input :cost
    = f.input :description, as: :text
    = f.input :document, as: :file
    - if f.object.document.exists?
      Este es el archivo actual del curso:
      = image_tag f.object.document.url(:thumb), class: "img-thumbnail"
    = f.input :registrable, as: :boolean, boolean_style: :inline
    .col-md-10.col-md-offset-1.controls
      = f.submit "Guardar", class: "btn btn-success btn-block btn-lg"
      = link_to "Regresar", admin_courses_url, class: "btn btn-default btn-lg btn-block"

app/views/admin/courses/index.html.haml
%br
%br
.container
  %br
  %h1 Cursos
  %br
  .col-sm-offset-10.col-sm-2
    = link_to new_admin_course_path, class: "btn btn-default" do
      %span.glyphicon.glyphicon-plus
      Crear Curso
  - if @courses.any?
    %table.table.table-stripped.space-top
      %thead
        %tr
          %th Titulo
          %th Precio al público
          %th Descripción
          %th
          %th
      %tbody
        - @courses.each do |course|
          %tr
            %td
              %strong= course.title
            %td= number_to_currency(course.cost, precision: 0)
            %td= course.description
            %td= link_to '', edit_admin_course_url(course), title: 'Editar', class: "glyphicon glyphicon-pencil"
            %td= link_to '', admin_course_path(course), method: :delete, title: 'Eliminar', data: {confirm: '¿Estás seguro?'}, class: "glyphicon glyphicon-remove"
  - else
    %br
    %br
    %p.well.space-top
      No se han encontrado cursos
    .form-group
      .col-sm-offset-10.col-sm-2
        = link_to 'Administrar usuarios', admin_users_url, :class => 'btn btn-default'

app/views/admin/courses/new.html.haml
.col-md-3.col-md-offset-4
  .text-center
    %h1 Nuevo Curso
    %hr
  = simple_form_for @course, as: @course, url: admin_courses_path(@course), html: {multipart: true} do |f|
    - if @course.errors.any?
      #errors
        %h2
        = pluralize(@course.errors.count, "error")
        No permitieron salvar el curso
        %ul
          - @course.errors.full_messages.each do |msg|
            %li= msg

    = f.input :title, autofocus: true
    = f.input :cost
    = f.input :description, as: :text
    = f.input :document, as: :file
    = f.submit "Crear Curso", class: "btn btn-success btn-block btn-sm"
    = link_to "Regresar", admin_courses_path

app/views/admin/entries/edit.html.haml
.col-md-3.col-md-offset-4
  .text-center
    %h1 Editar post
    %hr
  = simple_form_for @entry, url: admin_entry_url(@entry), html: {method: :put, autocomplete: 'off' } do |f|
    = f.input :url, autofocus: true
    .col-md-10.col-md-offset-1
      = f.submit "Guardar", class: "btn btn-success btn-block btn-lg"
      = link_to "Regresar", admin_entries_url, class: "btn btn-default btn-lg btn-block"

app/views/admin/entries/index.html.haml
%br
%br
.container
  %h1 Posts
  %br
  .col-sm-offset-10.col-sm-2
    = link_to new_admin_entry_path, class: "btn btn-default" do
      %span.glyphicon.glyphicon-plus
      Crear Post
  - if @entries
    %table.table.table-stripped.space-top
      %thead
        %tr
          %th URL
          %th Usuario que lo posteó
          %th
          %th
      %tbody
        - @entries.each do |entry|
          %tr
            %td= entry.url
            %td= entry.user.name
            %td= link_to '', edit_admin_entry_url(entry), title: 'Editar', class: "glyphicon glyphicon-pencil"
            %td= link_to '', admin_entry_path(entry), method: :delete, title: 'Eliminar', data: {confirm: '¿Estás seguro?'}, class: "glyphicon glyphicon-remove"
  - else
    %br
    %br
    %p.well.space-top
      No se han encontrado posts
    .form-group
      .col-sm-offset-10.col-sm-2

app/views/admin/entries/new.html.haml
.col-md-3.col-md-offset-4
  .text-center
    %h1 Nuevo Post
    %hr
  = simple_form_for @entry, as: @entry, url: admin_entries_path(@entry) do |f|
    - if @entry.errors.any?
      #errors
        %h2
        = pluralize(@entry.errors.count, "error")
        No permitieron salvar el post
        %ul
          - @course.errors.full_messages.each do |msg|
            %li= msg

    = f.input :url, autofocus: true
    = f.submit "Crear Post", class: "btn btn-success btn-block btn-sm"
    = link_to "Regresar", admin_entries_path

app/views/admin/users/edit.html.haml
.col-md-3.col-md-offset-4
  .text-center
    %h1 Editar usuario
    %hr
  = simple_form_for @user, url: admin_user_url(@user), html: {method: :put, autocomplete: 'off' } do |f|
    = f.input :name, autofocus: true
    = f.input :email
    = f.input :admin, as: :boolean, boolean_style: :inline
    .col-md-10.col-md-offset-1
      = f.submit "Guardar", class: "btn btn-success btn-block btn-lg"
      = link_to "Regresar", admin_users_url, class: "btn btn-default btn-lg btn-block"

app/views/admin/users/index.html.haml
%br
%br
.container
  %h1 Usuarios
  %br
  - if @users.any?
    %table.table.table-stripped.space-top
      %thead
        %tr
          %th Nombre
          %th Email
          %th Admin
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.email
            %td= user.admin
            %td= link_to '', edit_admin_user_url(user), title: 'Editar', class: 'glyphicon glyphicon-pencil'
  - else
    %p.well.space-top
      No se han encontrado usuarios
    .form-group
      .col-sm-offset-10.col-sm-2
        = link_to 'Regresar', admin_users_url, :class => 'btn btn-default btn-block'

app/views/home/_course_card.html.haml
.col-md-4
  .course
    .course-header
      = course.title
    .course-body
      - if course.cost
        %span.dollar $
        %span.amount= number_with_delimiter(course.cost, delimiter: ",")
        .price-note El costo del curso incluye materiales.
      .course-controls
        - if course.registrable
          - if course.title.include?('1')
            %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
              %input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
              %input{:name => "hosted_button_id", :type => "hidden", :value => "FZDANJLDYJD9E"}/
              %input{:alt => "PayPal, la forma más segura y rápida de pagar en línea.", :border => "0", :name => "submit", :src => "http://i.imgur.com/1MyNoHE.png?1", :type => "image"}/
              %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/es_XC/i/scr/pixel.gif", :width => "1"}/
          - elsif course.title.include?('2')
            %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
              %input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
              %input{:name => "hosted_button_id", :type => "hidden", :value => "VZHACARFKGFNS"}/
              %input{:alt => "PayPal, la forma más segura y rápida de pagar en línea.", :border => "0", :name => "submit", :src => "http://i.imgur.com/1MyNoHE.png?1", :type => "image"}/
              %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/es_XC/i/scr/pixel.gif", :width => "1"}/
          - else
            %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
              %input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
              %input{:name => "hosted_button_id", :type => "hidden", :value => "ESZUZ7GE9LSN8"}/
              %input{:alt => "PayPal, la forma más segura y rápida de pagar en línea.", :border => "0", :name => "submit", :src => "http://i.imgur.com/1MyNoHE.png?1", :type => "image"}/
              %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/es_XC/i/scr/pixel.gif", :width => "1"}/

    .course-description
      = raw course.description
      - if course.title.include?('1')
        = link_to 'Descargar PDF', '/N_1.pdf'
      - elsif course.title.include?('2')
        = link_to 'Descargar PDF', '/N_2.pdf'

app/views/home/index.html.haml
%header#home
  .text-vcenter
    %h1 Flores de Bach México
    %h3
      Cursos aprobados por
      %em The Bach Centre
      %small ®
    = link_to "#about", id: "continue-button", class: "glyphicon" do
      %span.glyphicon.glyphicon-chevron-down

/ second section - About

#about.pad-section
  .container
    .row
      .col-sm-5.text-center
        %h2 BIEP
        %p.lead (Bach International Education Programme - Programa Internacional de Educación Bach) Desde 1991, se imparte en más de 40 países transmitiendo fielmente las enseñanzas del Dr. Bach. Consta de 3 niveles con validéz internacional. Alma García es instructora certificada para los niveles 1, 2 y 3.
      .col-sm-2.text-center
        =image_tag 'bach_foundation.JPG', class: 'bach-divider'
      .col-sm-5.text-center
        %h2 Consulta
        %p.lead Descubre cómo este sistema te aporta la ayuda que necesitas, sintiéndote ecuchado y guiado para recobrar tu equilibrio emocional.

/ third section - Services
#services.pad-section
  .container
    %h2.text-center.light-text Servicios
    %hr
    .row.text-center
      .col-sm-4.col-xs-12
        %i.glyphicon.glyphicon-map-marker
        %h4 Cursos
        %p Cursos aprobados por el Bach Centre de Inglaterra con validéz para obtener la certificación como practitioner.
      .col-sm-4.col-xs-12
        %i.glyphicon.glyphicon-phone-alt
        %h4 Consulta
        %p Comunícate al 50014211 para programar tu cita o escríbenos a info@floresdebachmexico.com
      .col-sm-4.col-xs-12
        %i.glyphicon.glyphicon-bullhorn
        %h4 Otros servicios
        %p Asesoría a empresas y consulta en línea.


/ fourth section - Information
#information.pad-section
  .vertically-aligned
    %h2 "Treat the patients personality not his disease"
    %h3 Dr. Edward Bach

/ fifth section
#courses.pad-section
  .container
    %h1 Cursos
    .col-md-10.col-md-offset-1
      - @courses.each do |course|
        = render partial: "course_card", locals: {course: course}

/ Press section
#press.pad-section
  .container
    .row.text-center
      %h2 VISTO EN
    .row
      .col-md-10.col-md-offset-1
        .col-md-3.col-sm-3
          = image_tag "grupoimagenwhite.png", class: "img-responsive"
        .col-md-3.col-sm-3
          = image_tag "aztecatrecewhite.png", class: "img-responsive"
        .col-md-3.col-sm-3
          = image_tag "canaloncewhite.png", class: "img-responsive"
        .col-md-3.col-sm-3
          = image_tag "radioformulawhite.png", class: "img-responsive-responsive"

/ Contact
#contact
  .container
    %br
    %br
    .text-center
      %h2 Contáctanos
    .col-md-6.col-md-offset-3
      = form_for @contact_request, html: { role: "form", id: "contact-form" } do |f|
        .form-group
          %label Tu nombre *
          .controls
            = f.text_field :name, :class => 'form-control'
            %small.help-block
        .form-group
          %label Tu correo *
          .controls
            = f.email_field :email, :class => 'form-control'
            %small.help-block
        .form-group
          %label Mensaje
          .controls
            = f.text_area :message, :class => 'form-control', rows: 5
            %small.help-block
        .form-actions.text-right
          = f.submit 'Enviar', :class => 'btn btn-lg'
    .clearfix
    %br
    %br
    .text-center
      %h3 También escríbenos en nuestras redes sociales
%br
%br
%br

%hr
%br

#blog
  .container
    .text-center
      %h1 Blog y Noticias
      - if current_user.present?
        - @entries.each do |entry|
          .col-md-4
            = entry.url.html_safe
      - else
        %h3 Contenido exlusivo para miembros de la comunidad Flores de Bach México.
        = link_to 'Regístrate', new_user_registration_path

/ footer
%footer
  .container
    %hr
    .container
      %p.text-center
        © Flores de Bach México
        = Date.today.year

app/views/layouts/application.html.haml
!!!
%html{:lang => "es"}
  = render partial: "layouts/application/head"
  %body
    - if current_page?(root_path)
      = render partial: "layouts/home/navbar"
      = render partial: "layouts/home/flash"
    - else
      = render partial: "layouts/application/navbar"
      = render partial: "layouts/application/flash"
    = yield

app/views/layouts/application/_flash.html.haml
.container
  - if notice
    .alert.alert-application.alert-dismissable.alert-success.text-center
      %button.close{'data-dismiss' => 'alert', :type => 'button'} ×
      = notice
  - if alert
    .alert.alert-application.alert-dismissable.alert-danger.text-center
      %button.close{'data-dismiss' => 'alert', :type => 'button'} ×
      = alert

app/views/layouts/application/_head.html.haml
%head
  %title Flores de Bach México
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}

  //Google Analytics tracking code
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-3745777-1', 'auto');
    ga('send', 'pageview')

app/views/layouts/application/_navbar.html.haml
/ navigation panel
%nav#nav.navbar-default.navbar-static-top{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-collapse-main", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Flores de Bach México", root_path, class: "navbar-brand"
    #navbar-collapse-main.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if !user_signed_in?
          %li= link_to "Entrar", new_user_session_path
          %li= link_to "Registrarme", new_user_registration_path
        - else
          %li.dropdown
            = link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do
              = current_user.name
              %i.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Salir", destroy_user_session_path, method: :delete
          - if current_user.admin?
            %li.dropdown
              = link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do
                Administrar
                %i.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to "Usuarios", admin_users_path
                %li= link_to "Cursos", admin_courses_path
                %li= link_to "Posts", admin_entries_path

app/views/layouts/email.html.haml
!!! 5
%html
  %head
    %title Flores de Bach México
  %body
    %table(cellpadding="10" cellspacing="0" style="margin:0;padding:0 0 30px 0;background-color:#f4f5f7" width="100%")
      %tbody
        %tr
          %td
            %table(align="center" border="0" cellpadding="0" cellspacing="0" width="600")
              %tbody
                %tr
                  %td(style="background-color:#ffc602;height:15px;")
                %tr
                  %td(style="border:1px dotted #d6d7d8;border-top:none;border-bottom:3px solid #d6d7d8")
                    %table(align="center" border="0" cellpadding="30" cellspacing="0" width="100%")
                      %tbody
                        %tr
                          %td(style="background-color:#ffffff")
                            %p(style="text-align:center;margin:5px 0 25px 0;padding:0")
                            = yield
                %tr
                  %td(style="color:#9ab;font:normal 11px helvetica,sans-serif;text-align:center;padding:20px 0")
                    &copy; Flores de Bach México
                    %br/
                    %a{href: '#', style: 'color:#9ab', target: '_blank'} Pol&iacute;tica de Privacidad

app/views/layouts/home/_flash.html.haml
.container
  - if notice
    .alert.alert-dismissable.alert-success.text-center
      %button.close{'data-dismiss' => 'alert', :type => 'button'} ×
      = notice
  - if alert
    .alert.alert-dismissable.alert-danger.text-center
      %button.close{'data-dismiss' => 'alert', :type => 'button'} ×
      = alert

app/views/layouts/home/_navbar.html.haml
/ navigation panel
%nav#nav.navbar-default.navbar-fixed-top{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-collapse-main", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Flores de Bach México", root_path, class: "navbar-brand"
    #navbar-collapse-main.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Acerca', '#about'
        %li= link_to 'Servicios', '#services'
        %li= link_to 'Información', '#information'
        %li= link_to 'Contacto', '#contact'
        - if !user_signed_in?
          %li= link_to "Entrar", new_user_session_path
          %li= link_to "Registrarme", new_user_registration_path
        - else
          %li.dropdown
            = link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do
              = current_user.name
              %i.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Salir", destroy_user_session_path, method: :delete
          - if current_user.admin?
            %li.dropdown
              = link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do
                Administrar
                %i.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to "Usuarios", admin_users_path
                %li= link_to "Cursos", admin_courses_path
                %li= link_to "Posts", admin_entries_path